- name: vagrant basic setup
  hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
  - name: update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 36000

  tasks:

    - name: install a bunch of basic util packages 
      apt:
        pkg:
        - ntp
        - htop
        - mailutils
        - acl

    - name: Set the timezone to America/Toronto 
      timezone: "name=America/Toronto"

    - name: Make sure ntp is started, and is enabled on restart.
      service: name=ntp state=started enabled=yes
